use actix_web::{web, HttpResponse};
use chrono::Utc;
use sqlx::PgPool;
use uuid::Uuid;

/// Struct to model the inputed form data when sending a `POST` request through
/// [subscribe] endpoint.
#[derive(serde::Deserialize)]
pub struct FormData {
    email: String,
    name: String,
}

/// Endpoint to add new user to newsletter.
///
/// Responses:
/// - 200 OK: successful subscription
/// - 400 BAD REQUEST: name or email field is missing
///
/// It uses actix-web's [web::Form] extractor. The extractors are in charge of handling
/// failure responses. `actix-web` invokes [web::FromRequest]'s `from_request()`
/// (`FromRequest` is implemented by `Form` and any other extractor) for all `subscribe`'s
/// input arguments: in this case `Form::from_request`. `Form::from_request` tries to
/// deserialise the body into [FormData] (through `serde_urlencoded` and the `Deserialize`
/// implementation of [FormData]), automatically generated by
/// `#[derive(serde::Deserialize)]`.
///
/// If the extraction succeed, the hanlder is called normally, but
/// if it fails, then the corresponding error (`400 BAD REQUEST`) is returned to the
/// caller and the handler is never invoked; when `from_request()` returns a
/// [actix_web::Error] it can be converted to [HttpResponse].
///
/// Similarly, the [web::Data] extractor allows us to get the connection pool from
/// application state as defined in `run`. In other contexts, this could be referred
/// as _dependency injection_.
pub async fn subscribe(
    form: web::Form<FormData>,
    pool: web::Data<PgPool>,
) -> Result<HttpResponse, HttpResponse> {
    sqlx::query!(
        r#"
        INSERT INTO subscriptions (id, email, name, subscribed_at)
        VALUES ($1, $2, $3, $4)
        "#,
        Uuid::new_v4(),
        form.email,
        form.name,
        Utc::now()
    )
    // sqlx doesn't allow to run multiple queries concurrently over the same DB connection.
    // That's why it requires a mutable reference (that is, a "unique" refence) to the
    // connection. We can't get a mutable reference from web::Data, so we need to use
    // something else, like PgPool in this case.
    .execute(pool.as_ref())
    .await
    .map_err(|e| {
        eprintln!("Failed to execute query: {}", e);
        HttpResponse::InternalServerError().finish()
    })?;

    Ok(HttpResponse::Ok().finish())
}
