use actix_web::{web, HttpResponse};

/// Struct to model the inputed form data when sending a `POST` request through
/// [subscribe] endpoint.
#[derive(serde::Deserialize)]
pub struct FormData {
    email: String,
    name: String,
}

/// Endpoint to add new user to newsletter.
///
/// Responses:
/// - 200 OK: successful subscription
/// - 400 BAD REQUEST: name or email field is missing
///
/// It uses actix-web's [web::Form] extractor. The extractors are in charge of handling
/// failure responses. `actix-web` invokes [web::FromRequest]'s `from_request()`
/// (`FromRequest` is implemented by `Form` and any other extractor) for all `subscribe`'s
/// input arguments: in this case `Form::from_request`. `Form::from_request` tries to
/// deserialise the body into [FormData] (through `serde_urlencoded` and the `Deserialize`
/// implementation of [FormData]), automatically generated by
/// `#[derive(serde::Deserialize)]`.
///
/// If the extraction succeed, the hanlder is called normally, but
/// if it fails, then the corresponding error (`400 BAD REQUEST`) is returned to the
/// caller and the handler is never invoked; when `from_request()` returns a
/// [actix_web::Error] it can be converted to [HttpResponse].
pub async fn subscribe(_form: web::Form<FormData>) -> HttpResponse {
    HttpResponse::Ok().finish()
}
